Accessing mongodb and discarding env vars
GeoSales-Evolution/multi-tenant-uploader pull request #31
Opened 2023-05-19 13:38 UTC by brenoaraujolima

Depends on #29 

Replacing the use of env variables for rescuing these variables from mongo database. 

To access database properly, fill `.env` this way: [dot-env](https://discord.com/channels/874270508038897696/1092539576964366487/1109112408666030220)

2023-05-19 17:20 UTC, jeffque requested changes
This should not be dependent on #29, but the other way around

2023-05-19 18:29 UTC, brenoaraujolima commented
> This should not be dependent on #29, but the other way around

Rebased on main.

2023-05-23 12:32 UTC, brenoaraujolima commented on .env.example
> +DB_SERVER=
These variables need to be created as a secret in repository's settings.

2023-05-23 17:42 UTC, brenoaraujolima commented on .env.example
> +DB_USER=
Put these variables in CI jobs

2023-05-23 19:35 UTC, uxjp approved these changes

2023-05-25 14:07 UTC, williamvb approved these changes

2023-05-25 14:54 UTC, merged